### ISSUE TITLE
Opening multiple projects PHPstorm

### ISSUE THREAD

**Issue by luukverhoeven** [bchatard/alfred-jetbrains#45]
**Describe the bug**
If you already have one project open in PHPstorm it doesn't allows opening another.

**To Reproduce**
1. Open a project in PHPstorm.
2. Use Alfred to open another project -> pstorm projectname.
3. There is a MacOS notification it opened the requested project.
4. It focus on previous project and the request project isn't openend.

**Expected behavior**
I expect that multiple PHPstorm projects can be openend. Within PHPstorm itself it works correctly.

Q | A
--- | ---
Workflow version | 1.0.12
OSX Version | 10.14.6
Alfred Version | 4.0.3
JetBrains Product/Version | PhpStorm / 2019.2
Installation type | _classic .dmg
Node version | X
NPM version | X
---
There are no errors or exception triggered.

**Comment by bchatard** [comment]
Hi @luukverhoeven ,

Did you update your *Command line launcher script* after the update to 2019.2?

**Comment by luukverhoeven** [comment]
Hi @bchatard,

Thanks for your response. Yes, it's the latest launcher.
![image](https://user-images.githubusercontent.com/995760/61934980-cad75200-af89-11e9-8fe8-f9c08b9bcbae.png)

Screencast
https://www.youtube.com/watch?v=SWVAgquJ-oY

**Comment by bchatard** [comment]
can you give me the content of `/usr/local/bin/pstorm`?

**Comment by luukverhoeven** [comment]
Sure, 
https://gist.github.com/luukverhoeven/2ead9b6308436b9e34fa2f9a20adba47

**Comment by bchatard** [comment]
ok seems good

Can you try the following:
1. Close PHPStorm
2. In your terminal, go to a project dir and run `pstorm .`
3. wait for project opening 
4. In your terminal, go to another project dir and run `pstorm .`

How many PHPStorm project are opened?

**Comment by luukverhoeven** [comment]
That command works correct. 
- 2 projects are launched from it.

**Comment by bchatard** [comment]
By default the workflow works with a bin named `phpstorm`, did you update the workflow to use `pstorm`?

**Comment by luukverhoeven** [comment]
How do you mean `did you update the workflow to use pstorm?`

**Comment by bchatard** [comment]
By default this workflow use a bin named `phpstorm` to open project with PHPStorm (which is the default bin name since few versions).

Previously you mentioned that you use `pstorm` which unknown by this workflow. 

So my guess is that you have a bin `phpstorm` referenced with an older PHPStorm version, in that case this bin can open only one instance (I don't known how).

You have two choices:
1. change bin name in your PHPStorm to use `phpstorm`
2. update the workflow configuration to use `pstorm` instead of `phpstorm` ([doc](https://github.com/bchatard/alfred-jetbrains/blob/master/doc/customisation/product.md))

Please let me know if you already have a bin named `phpstorm` (and it's content if exists)

**Comment by luukverhoeven** [comment]
Thanks! Works correct now.
